# -*- coding: utf-8 -*-
from . import healthcare_practice
from . import healthcare_patient
from . import healthcare_appointment
from . import healthcare_consultation
from . import healthcare_care_plan
from . import healthcare_referral
from . import healthcare_disease
from . import healthcare_lab
from . import healthcare_medication
from . import healthcare_allied
from . import healthcare_automation
from . import healthcare_population_report
from . import healthcare_dashboard
from . import crm_lead
from . import healthcare_ward
from . import healthcare_room
from . import healthcare_bed
from . import healthcare_admission
